import works from './works'
import testimonials from './testimonials'
import brands from './brands'
import abouts from './about/abouts'
import historys from './about/historys'
import visis from './about/visis'
import misis from './about/misis'
import perans from './about/perans'
import kegiatans from './about/kegiatans'
import yayasans from './about/yayasans'
import uuandpps from './about/uuandpps'
import ccss from './about/ccss'
import homeschoolings from './about/homeschoolings'
import faqss from './about/faqss'
import graduations from './graduations'
import graduationseniors from './graduationseniors'
import graduationjuniors from './graduationjuniors'
import graduationelementarys  from './graduationelementarys'
import teachers  from './teachers'
import academic  from './academics'
import experiences from './experiences'
import skills from './skills'
import workExperience from './workExperience'
import contact from './contact'
import keluargas from './about/keluargas'
import masyarakats from './about/masyarakats'
import negaras from './about/negaras'
import psrs from './about/psrs'


export const schemaTypes = [works, abouts, keluargas, masyarakats, negaras, psrs, historys, visis, misis, perans, kegiatans, homeschoolings, yayasans, uuandpps, ccss, faqss, graduations, graduationseniors, graduationjuniors, graduationelementarys, teachers, academic, brands, experiences, workExperience, contact, skills, testimonials]
